language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PACKAGE="fd-send-recv"
  matrix:
  - DISTRO="debian-testing" OCAML_VERSION="4.02.3"
  - DISTRO="ubuntu-14.04" OCAML_VERSION="4.02.3"
  - DISTRO="ubuntu-15.10" OCAML_VERSION="4.02.3"
  - DISTRO="centos-7" OCAML_VERSION="4.02.3"
  - DISTRO="centos-6" OCAML_VERSION="4.02.3"
  - DISTRO="fedora-23" OCAML_VERSION="4.02.3"
